module AtomsData 

# MISSING: 
#   2 (He), 25 (Mn),85 (At), 87 (Fr), 88 (Ra), ≥ 92 (U and beyond)
#  
# added manually: Ne (10), Ar (18),  Kr (36), Xe (54), 55 (Cs), 
#                 64 (Gd), 67 (Ho), 68 (Er), 71 (Lu)

const LENGTHSCALES = Dict(
    1 => Dict("bond_len" => [1.2, "NB VASP auto_length_scale"],
              "min_bond_len" => [0.75, "NB VASP auto_length_scale"],
              "other links" => Dict(),
              "vol_per_atom" => [3.4, "NB VASP auto_length_scale"]),
    11 => Dict("bond_len" => [3.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [35, "NB VASP auto_length_scale"]),
    12 => Dict("bond_len" => [3.2, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [23, "NB VASP auto_length_scale"]),
    13 => Dict("bond_len" => [2.9, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.5, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [17, "NB VASP auto_length_scale"]),
    14 => Dict("bond_len" => [2.4, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.3, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [20, "NB VASP auto_length_scale"]),
    15 => Dict("bond_len" => [2.5, "NB VASP auto_length_scale"],
               "min_bond_len" => [1.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [15, "NB VASP auto_length_scale"]),
    16 => Dict("bond_len" => [2.3, "NB VASP auto_length_scale"],
               "min_bond_len" => [1.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [17, "NB VASP auto_length_scale"]),
    17 => Dict("bond_len" => [2.6, "NB VASP auto_length_scale"],
               "min_bond_len" => [2, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [36, "NB VASP auto_length_scale"]),
    19 => Dict("bond_len" => [4.6, "NB VASP auto_length_scale"],
               "min_bond_len" => [3.5, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [71, "NB VASP auto_length_scale"]),
    20 => Dict("bond_len" => [3.8, "NB VASP auto_length_scale"],
               "min_bond_len" => [3, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [41, "NB VASP auto_length_scale"]),
    21 => Dict("bond_len" => [3.2, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.6, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [22, "NB VASP auto_length_scale"]),
    22 => Dict("bond_len" => [2.9, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.4, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [17, "NB VASP auto_length_scale"]),
    23 => Dict("bond_len" => [2.6, "NB VASP auto_length_scale"],
               "min_bond_len" => [1.8, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [13, "NB VASP auto_length_scale"]),
    24 => Dict("bond_len" => [2.5, "NB VASP auto_length_scale"],
               "min_bond_len" => [1.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [12, "NB VASP auto_length_scale"]),
    26 => Dict("bond_len" => [2.5, "NB VASP auto_length_scale"],
               "min_bond_len" => [1.8, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [11, "NB VASP auto_length_scale"]),
    27 => Dict("bond_len" => [2.5, "NB VASP auto_length_scale"],
               "min_bond_len" => [2, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [11, "NB VASP auto_length_scale"]),
    28 => Dict("bond_len" => [2.5, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.1, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [11, "NB VASP auto_length_scale"]),
    29 => Dict("bond_len" => [2.6, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.2, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [12, "NB VASP auto_length_scale"]),
    3 => Dict("bond_len" => [3, "NB VASP auto_length_scale"],
              "min_bond_len" => [2.4, "NB VASP auto_length_scale"],
              "other links" => Dict(),
              "vol_per_atom" => [20, "NB VASP auto_length_scale"]),
    30 => Dict("bond_len" => [2.8, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.5, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [15, "NB VASP auto_length_scale"]),
    31 => Dict("bond_len" => [3, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.5, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [19, "NB VASP auto_length_scale"]),
    32 => Dict("bond_len" => [2.5, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.1, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [24, "NB VASP auto_length_scale"]),
    33 => Dict("bond_len" => [2.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.1, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [20, "NB VASP auto_length_scale"]),
    34 => Dict("bond_len" => [2.8, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.2, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [22, "NB VASP auto_length_scale"]),
    35 => Dict("bond_len" => [2.8, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.3, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [29, "NB VASP auto_length_scale"]),
    37 => Dict("bond_len" => [4.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [3.7, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [81, "NB VASP auto_length_scale"]),
    38 => Dict("bond_len" => [4.2, "NB VASP auto_length_scale"],
               "min_bond_len" => [3.8, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [54, "NB VASP auto_length_scale"]),
    39 => Dict("bond_len" => [3.6, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [33, "NB VASP auto_length_scale"]),
    4 => Dict("bond_len" => [2.2, "NB VASP auto_length_scale"],
              "min_bond_len" => [2.1, "NB VASP auto_length_scale"],
              "other links" => Dict(),
              "vol_per_atom" => [7.9, "NB VASP auto_length_scale"]),
    40 => Dict("bond_len" => [3.2, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.3, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [23, "NB VASP auto_length_scale"]),
    41 => Dict("bond_len" => [2.9, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.1, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [18, "NB VASP auto_length_scale"]),
    42 => Dict("bond_len" => [2.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [16, "NB VASP auto_length_scale"]),
    43 => Dict("bond_len" => [2.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [14, "NB VASP auto_length_scale"]),
    44 => Dict("bond_len" => [2.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.1, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [14, "NB VASP auto_length_scale"]),
    45 => Dict("bond_len" => [2.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.2, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [14, "NB VASP auto_length_scale"]),
    46 => Dict("bond_len" => [2.8, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.4, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [15, "NB VASP auto_length_scale"]),
    47 => Dict("bond_len" => [2.9, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.6, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [18, "NB VASP auto_length_scale"]),
    48 => Dict("bond_len" => [3.2, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [23, "NB VASP auto_length_scale"]),
    49 => Dict("bond_len" => [3.4, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.8, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [27, "NB VASP auto_length_scale"]),
    5 => Dict("bond_len" => [1.8, "NB VASP auto_length_scale"],
              "min_bond_len" => [1.6, "NB VASP auto_length_scale"],
              "other links" => Dict(),
              "vol_per_atom" => [8.3, "NB VASP auto_length_scale"]),
    50 => Dict("bond_len" => [2.9, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.6, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [36, "NB VASP auto_length_scale"]),
    51 => Dict("bond_len" => [3.1, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.5, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [29, "NB VASP auto_length_scale"]),
    52 => Dict("bond_len" => [3.2, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.6, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [32, "NB VASP auto_length_scale"]),
    53 => Dict("bond_len" => [3.2, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.7, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [39, "NB VASP auto_length_scale"]),
    56 => Dict("bond_len" => [4.3, "NB VASP auto_length_scale"],
               "min_bond_len" => [3.5, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [59, "NB VASP auto_length_scale"]),
    57 => Dict("bond_len" => [3.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.6, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [36, "NB VASP auto_length_scale"]),
    58 => Dict("bond_len" => [3.4, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.6, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [27, "NB VASP auto_length_scale"]),
    59 => Dict("bond_len" => [3.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.8, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [36, "NB VASP auto_length_scale"]),
    6 => Dict("bond_len" => [1.4, "NB VASP auto_length_scale"],
              "min_bond_len" => [1.3, "NB VASP auto_length_scale"],
              "other links" => Dict(),
              "vol_per_atom" => [5.7, "NB VASP auto_length_scale"]),
    60 => Dict("bond_len" => [3.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.6, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [35, "NB VASP auto_length_scale"]),
    61 => Dict("bond_len" => [3.6, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.7, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [34, "NB VASP auto_length_scale"]),
    62 => Dict("bond_len" => [3.6, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.7, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [33, "NB VASP auto_length_scale"]),
    64 => Dict("bond_len" => [3.6, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [33, "NB VASP auto_length_scale"]),
    65 => Dict("bond_len" => [3.6, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [32, "NB VASP auto_length_scale"]),
    66 => Dict("bond_len" => [3.5, "NB VASP auto_length_scale"],
               "min_bond_len" => [3.1, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [31, "NB VASP auto_length_scale"]),
    69 => Dict("bond_len" => [3.5, "NB VASP auto_length_scale"],
               "min_bond_len" => [3.1, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [30, "NB VASP auto_length_scale"]),
    7 => Dict("bond_len" => [1.6, "NB VASP auto_length_scale"],
              "min_bond_len" => [1.1, "NB VASP auto_length_scale"],
              "other links" => Dict(),
              "vol_per_atom" => [9.2, "NB VASP auto_length_scale"]),
    70 => Dict("bond_len" => [3.8, "NB VASP auto_length_scale"],
               "min_bond_len" => [3.3, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [39, "NB VASP auto_length_scale"]),
    72 => Dict("bond_len" => [3.2, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.6, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [22, "NB VASP auto_length_scale"]),
    73 => Dict("bond_len" => [2.9, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.1, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [18, "NB VASP auto_length_scale"]),
    74 => Dict("bond_len" => [2.8, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.1, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [16, "NB VASP auto_length_scale"]),
    75 => Dict("bond_len" => [2.8, "NB VASP auto_length_scale"],
               "min_bond_len" => [2, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [15, "NB VASP auto_length_scale"]),
    76 => Dict("bond_len" => [2.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.1, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [14, "NB VASP auto_length_scale"]),
    77 => Dict("bond_len" => [2.7, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.2, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [15, "NB VASP auto_length_scale"]),
    78 => Dict("bond_len" => [2.8, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.3, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [16, "NB VASP auto_length_scale"]),
    79 => Dict("bond_len" => [2.9, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.5, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [18, "NB VASP auto_length_scale"]),
    8 => Dict("bond_len" => [1.7, "NB VASP auto_length_scale"],
              "min_bond_len" => [1.2, "NB VASP auto_length_scale"],
              "other links" => Dict(),
              "vol_per_atom" => [11, "NB VASP auto_length_scale"]),
    80 => Dict("bond_len" => [3.3, "NB VASP auto_length_scale"],
               "min_bond_len" => [3, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [28, "NB VASP auto_length_scale"]),
    81 => Dict("bond_len" => [3.4, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [31, "NB VASP auto_length_scale"]),
    82 => Dict("bond_len" => [3.5, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.9, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [31, "NB VASP auto_length_scale"]),
    83 => Dict("bond_len" => [3.3, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.7, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [34, "NB VASP auto_length_scale"]),
    84 => Dict("bond_len" => [3.3, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.8, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [36, "NB VASP auto_length_scale"]),
    89 => Dict("bond_len" => [4, "NB VASP auto_length_scale"],
               "min_bond_len" => [3.5, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [46, "NB VASP auto_length_scale"]),
    9 => Dict("bond_len" => [2.1, "NB VASP auto_length_scale"],
              "min_bond_len" => [1.4, "NB VASP auto_length_scale"],
              "other links" => Dict(),
              "vol_per_atom" => [15, "NB VASP auto_length_scale"]),
    90 => Dict("bond_len" => [3.6, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.7, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [32, "NB VASP auto_length_scale"]),
    91 => Dict("bond_len" => [3.3, "NB VASP auto_length_scale"],
               "min_bond_len" => [2.4, "NB VASP auto_length_scale"],
               "other links" => Dict(),
               "vol_per_atom" => [25, "NB VASP auto_length_scale"]), 
   #  ------ MANUAL ADDITIONS FROM ATOMSBUILDER 
  55 => Dict{String, Vector{Any}}("bond_len"=>[5.23945, "AtomsBuilder data"]),
  54 => Dict{String, Vector{Any}}("bond_len"=>[4.38406, "AtomsBuilder data"]),
  63 => Dict{String, Vector{Any}}("bond_len"=>[3.99238, "AtomsBuilder data"]),
  10 => Dict{String, Vector{Any}}("bond_len"=>[3.13248, "AtomsBuilder data"]),
  18 => Dict{String, Vector{Any}}("bond_len"=>[3.71938, "AtomsBuilder data"]),
  36 => Dict{String, Vector{Any}}("bond_len"=>[4.04465, "AtomsBuilder data"]),
  67 => Dict{String, Vector{Any}}("bond_len"=>[3.48854, "AtomsBuilder data"]),
  68 => Dict{String, Vector{Any}}("bond_len"=>[3.46905, "AtomsBuilder data"]),
  71 => Dict{String, Vector{Any}}("bond_len"=>[3.44157, "AtomsBuilder data"])   
)

end
